program_config:
  output_folder:
  - DATE
  - Custom output folder. Use 'DATE' for outputs/fDD-MM-YYYY__HH-MM-SS.
logger_config:
  level:
  - INFO
  - 'Logging level. One of: DEBUG, INFO, WARNING, ERROR, CRITICAL.'
  config_file:
  - config.json
  - Path to the logging configuration file.
wallet_config:
  token:
  - hoi
  - The token for the wallet. Default is 'hoi'.
  retry:
  - 3299
  - null
  test:
  - hi:
    - doei
    - null
  - null
broker_config:
  base_url:
  - <str>
  - null
  wallet_map:
  - '{"str": "str", "str": "str"}'
  - null
